### ISSUE TITLE
Error in command for making a service plan available to org

### ISSUE THREAD

**Issue by jhsware** [ActiveState/stackato-doc#2]
Not sure if this is the right place, but https://github.com/ActiveState/stackato-doc/blob/master/admin/reference/add-service.rst

The docs says:

    $ stackato update-service-plan --public echoservice

But should say:

    $ stackato update-service-plan --public default

**Comment by philwhln** [comment]
Thanks @jhsware! We'll correct this. Cc @troytop

**Comment by troytop** [comment]
At first I didn't think the example was wrong to start with, but it looks like the 'stackato' cli command doesn't clarify that the 'vendor' information is mandatory:

    $ stackato help update-service-plan
    stackato update-service-plan [OPTIONS] [<name>] [<newname>]
        Update the target's knowledge of the named service plan. 

I'll try to fix both.

**Comment by troytop** [comment]
@jhsware I'm pretty sure this fixes the immediate issue. We'll be looking at bringing the command syntax in line with what's in the current 'cf' client
